name: Publish Docker image

on:
  push:
    branches: [ "main" ]

jobs:
  push_tools:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_TOOLS_VERSION: 9123335
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          context: .
          file: ./tools/Dockerfile
          platforms: linux/amd64
          build-args: |
            ANDROID_SDK_TOOLS_VERSION=${{ env.ANDROID_SDK_TOOLS_VERSION }}
          push: true
          tags: avetkhov/android-sdk:tools

  push_sdk:
    needs: push_tools
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: 33
            build-tools: 33.0.1
          - platform: 32
            build-tools: 32.0.0
          - platform: 31
            build-tools: 31.0.0
          - platform: 30
            build-tools: 30.0.3
          - platform: 29
            build-tools: 29.0.3
          - platform: 28
            build-tools: 28.0.3
          - platform: 27
            build-tools: 27.0.3
          - platform: 26
            build-tools: 26.0.3
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          build-args: |
            ANDROID_PLATFORM_VERSION=${{ matrix.platform }}
            ANDROID_BUILD_TOOLS_VERSION=${{ matrix.build-tools }}
          push: true
          tags: |
            avetkhov/android-sdk:${{ matrix.platform }}